# Generated by Django 4.2.4 on 2023-10-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test_alter_books_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
