# Generated by Django 4.2.4 on 2023-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='month',
            field=models.CharField(default='November'),
        ),
    ]
